### ISSUE TITLE
./build-dev.sh command results in error

### ISSUE THREAD

**Issue by weslexcore** [InsidiousMind/material-bliss-jekyll-theme#1]
Running the dev command results in this error output - 

```
Warning: Material-UI: userAgent should be supplied in the muiTheme context for server-side rendering.
Warning: validateDOMNesting(...): Text nodes cannot appear as a child of <html>. See Default > html > #text.
Warning: validateDOMNesting(...): <script> cannot appear as a child of <html>. See Default > html > script.
null
null
sed: 1: "src/_layouts/post.html": unterminated substitute pattern
```

**Comment by insipx** [comment]
Hey @Wmclaug2 

If you could provide what Operating System and Version you are on, I could get this error fixed ASAP

thanks for reporting in :)

**Comment by weslexcore** [comment]
macOS Sierra v 10.12.3

Thank you for the quick response, @InsidiousMind!

**Comment by insipx** [comment]
@Wmclaug2 

No problem!

Should be fixed. I got rid of the sed commands in ./generate-static which were causing the issue. What sed once did is now accomplished in react-dev/render_to_file.js

This should fix the issue with sed on MacOS

feel free to report back in if it isn't actually fixed/have any other issues
